{% macro map_country_to_code(column) %}
case 
    when {{ column }} = "Afghanistan"
                                                                                            then "AF"
    when {{ column }} = "Albania"
                                                                                            then "AL"
    when {{ column }} = "Algeria"
                                                                                            then "DZ"
    when {{ column }} = "American Samoa"
                                                                                            then "AS"
    when {{ column }} = "Andorra"
                                                                                            then "AD"
    when {{ column }} = "Angola"
                                                                                            then "AO"
    when {{ column }} = "Anguilla"
                                                                                            then "AI"
    when {{ column }} = "Antarctica"
                                                                                            then "AQ"
    when {{ column }} in ("Antigua and Barbuda", "Antigua & Barbuda")
                                                                                            then "AG"
    when {{ column }} = "Argentina"
                                                                                            then "AR"
    when {{ column }} = "Armenia"
                                                                                            then "AM"
    when {{ column }} = "Aruba"
                                                                                            then "AW"
    when {{ column }} = "Australia"
                                                                                            then "AU"
    when {{ column }} = "Austria"
                                                                                            then "AT"
    when {{ column }} = "Azerbaijan"
                                                                                            then "AZ"
    when {{ column }} in ("Bahamas (the)", "Bahamas")
                                                                                            then "BS"
    when {{ column }} = "Bahrain"
                                                                                            then "BH"
    when {{ column }} = "Bangladesh"
                                                                                            then "BD"
    when {{ column }} = "Barbados"
                                                                                            then "BB"
    when {{ column }} = "Belarus"
                                                                                            then "BY"
    when {{ column }} = "Belgium"
                                                                                            then "BE"
    when {{ column }} = "Belize"
                                                                                            then "BZ"
    when {{ column }} = "Benin"
                                                                                            then "BJ"
    when {{ column }} = "Bermuda"
                                                                                            then "BM"
    when {{ column }}   = "Bhutan"
                                                                                            then "BT"
    when {{ column }}   in ("Bolivia (Plurinational State of)", "Bolivia")
                                                                                            then "BO"
    when {{ column }}   = "Bonaire, Sint Eustatius and Saba"
                                                                                            then "BQ"
    when {{ column }}   in ("Bosnia and Herzegovina", "Bosnia & Herzegovina")
                                                                                            then "BA"
    when {{ column }}   = "Botswana"
                                                                                            then "BW"
    when {{ column }}   = "Bouvet Island"
                                                                                            then "BV"
    when {{ column }}   = "Brazil"
                                                                                            then "BR"
    when {{ column }}   in ("British Indian Ocean Territory (the)", "British Indian Ocean Territory")
                                                                                            then "IO"
    when {{ column }}   in ("Brunei Darussalam", "Brunei")
                                                                                            then "BN"
    when {{ column }}   = "Bulgaria"
                                                                                            then "BG"
    when {{ column }}   = "Burkina Faso"
                                                                                            then "BF"
    when {{ column }}   = "Burundi"
                                                                                            then "BI"
    when {{ column }}   in ("Cabo Verde", "Cape Verde")
                                                                                            then "CV"
    when {{ column }}   = "Cambodia"
                                                                                            then "KH"
    when {{ column }}   = "Cameroon"
                                                                                            then "CM"
    when {{ column }}   = "Canada"
                                                                                            then "CA"
    when {{ column }}   in ("Cayman Islands (the)", "Cayman Islands")
                                                                                            then "KY"
    when {{ column }}   in ("Central African Republic (the)", "Central African Republic")
                                                                                            then "CF"
    when {{ column }}   = "Chad"
                                                                                            then "TD"
    when {{ column }}   = "Chile"
                                                                                            then "CL"
    when {{ column }}   = "China"
                                                                                            then "CN"
    when {{ column }}   = "Christmas Island"
                                                                                            then "CX"
    when {{ column }}   = "Cocos (Keeling) Islands (the)"
                                                                                            then "CC"
    when {{ column }}   = "Colombia"
                                                                                            then "CO"
    when {{ column }}   = "Comoros (the)"
                                                                                            then "KM"
    when {{ column }}   in ("Congo (the Democratic Republic of the)", "Congo - Kinshasa")
                                                                                            then "CD"
    when {{ column }}   in ("Congo (the)", "Congo - Brazzaville")
                                                                                            then "CG"
    when {{ column }}   in ("Cook Islands (the)", "Cook Islands")
                                                                                            then "CK"
    when {{ column }}   = "Costa Rica"
                                                                                            then "CR"
    when {{ column }}   = "Croatia"
                                                                                            then "HR"
    when {{ column }}   = "Cuba"
                                                                                            then "CU"
    when {{ column }}   = "Curaçao"
                                                                                            then "CW"
    when {{ column }}   = "Cyprus"
                                                                                            then "CY"
    when {{ column }}   = "Czechia"
                                                                                            then "CZ"
    when {{ column }}   in ("Côte d'Ivoire", "Côte d’Ivoire")
                                                                                            then "CI"
    when {{ column }}   = "Denmark"
                                                                                            then "DK"
    when {{ column }}   = "Djibouti"
                                                                                            then "DJ"
    when {{ column }}   = "Dominica"
                                                                                            then "DM"
    when {{ column }}   in ("Dominican Republic (the)", "Dominican Republic")
                                                                                            then "DO"
    when {{ column }}   = "Ecuador"
                                                                                            then "EC"
    when {{ column }}   = "Egypt"
                                                                                            then "EG"
    when {{ column }}   = "El Salvador"
                                                                                            then "SV"
    when {{ column }}   = "Equatorial Guinea"
                                                                                            then "GQ"
    when {{ column }}   = "Eritrea"
                                                                                            then "ER"
    when {{ column }}   = "Estonia"
                                                                                            then "EE"
    when {{ column }}   = "Eswatini"
                                                                                            then "SZ"
    when {{ column }}   = "Ethiopia"
                                                                                            then "ET"
    when {{ column }}   in ("Falkland Islands (the) [Malvinas]", "Falkland Islands (Islas Malvinas)")
                                                                                            then "FK"
    when {{ column }}   in ("Faroe Islands (the)", "Faroe Islands")
                                                                                            then "FO"
    when {{ column }}   = "Fiji"
                                                                                            then "FJ"
    when {{ column }}   = "Finland"
                                                                                            then "FI"
    when {{ column }}   = "France"
                                                                                            then "FR"
    when {{ column }}   = "French Guiana"
                                                                                            then "GF"
    when {{ column }}   = "French Polynesia"
                                                                                            then "PF"
    when {{ column }}   = "French Southern Territories (the)"
                                                                                            then "TF"
    when {{ column }}   = "Gabon"
                                                                                            then "GA"
    when {{ column }}   in ("Gambia (the)", "Gambia")
                                                                                            then "GM"
    when {{ column }}   = "Georgia"
                                                                                            then "GE"
    when {{ column }}   = "Germany"
                                                                                            then "DE"
    when {{ column }}   = "Ghana"
                                                                                            then "GH"
    when {{ column }}   = "Gibraltar"
                                                                                            then "GI"
    when {{ column }}   = "Greece"
                                                                                            then "GR"
    when {{ column }}   = "Greenland"
                                                                                            then "GL"
    when {{ column }}   = "Grenada"
                                                                                            then "GD"
    when {{ column }}   = "Guadeloupe"
                                                                                            then "GP"
    when {{ column }}   = "Guam"
                                                                                            then "GU"
    when {{ column }}   = "Guatemala"
                                                                                            then "GT"
    when {{ column }}   = "Guernsey"
                                                                                            then "GG"
    when {{ column }}   = "Guinea"
                                                                                            then "GN"
    when {{ column }}   = "Guinea-Bissau"
                                                                                            then "GW"
    when {{ column }}   = "Guyana"
                                                                                            then "GY"
    when {{ column }}   = "Haiti"
                                                                                            then "HT"
    when {{ column }}   = "Heard Island and McDonald Islands"
                                                                                            then "HM"
    when {{ column }}   = "Holy See (the)"
                                                                                            then "VA"
    when {{ column }}   = "Honduras"
                                                                                            then "HN"
    when {{ column }}   = "Hong Kong"
                                                                                            then "HK"
    when {{ column }}   = "Hungary"
                                                                                            then "HU"
    when {{ column }}   = "Iceland"
                                                                                            then "IS"
    when {{ column }}   = "India"
                                                                                            then "IN"
    when {{ column }}   = "Indonesia"
                                                                                            then "ID"
    when {{ column }}   in ("Iran (Islamic Republic of)", "Iran")
                                                                                            then "IR"
    when {{ column }}   = "Iraq"
                                                                                            then "IQ"
    when {{ column }}   = "Ireland"
                                                                                            then "IE"
    when {{ column }}   = "Isle of Man"
                                                                                            then "IM"
    when {{ column }}   = "Israel"
                                                                                            then "IL"
    when {{ column }}   = "Italy"
                                                                                            then "IT"
    when {{ column }}   = "Jamaica"
                                                                                            then "JM"
    when {{ column }}   = "Japan"
                                                                                            then "JP"
    when {{ column }}   = "Jersey"
                                                                                            then "JE"
    when {{ column }}   = "Jordan"
                                                                                            then "JO"
    when {{ column }}   = "Kazakhstan"
                                                                                            then "KZ"
    when {{ column }}   = "Kenya"
                                                                                            then "KE"
    when {{ column }}   = "Kiribati"
                                                                                            then "KI"
    when {{ column }}   = "Korea (the Democratic People's Republic of)"
                                                                                            then "KP"
    when {{ column }}   in ("Korea (the Republic of)", "South Korea")
                                                                                            then "KR"
    when {{ column }}   = "Kosovo"
                                                                                            then "XK"
    when {{ column }}   = "Kuwait"
                                                                                            then "KW"
    when {{ column }}   = "Kyrgyzstan"
                                                                                            then "KG"
    when {{ column }}   in ("Lao People's Democratic Republic (the)", "Laos")
                                                                                            then "LA"
    when {{ column }}   = "Latvia"
                                                                                            then "LV"
    when {{ column }}   = "Lebanon"
                                                                                            then "LB"
    when {{ column }}   = "Lesotho"
                                                                                            then "LS"
    when {{ column }}   = "Liberia"
                                                                                            then "LR"
    when {{ column }}   = "Libya"
                                                                                            then "LY"
    when {{ column }}   = "Liechtenstein"
                                                                                            then "LI"
    when {{ column }}   = "Lithuania"
                                                                                            then "LT"
    when {{ column }}   = "Luxembourg"
                                                                                            then "LU"
    when {{ column }}   = "Macao"
                                                                                            then "MO"
    when {{ column }}   = "Madagascar"
                                                                                            then "MG"
    when {{ column }}   = "Malawi"
                                                                                            then "MW"
    when {{ column }}   = "Malaysia"
                                                                                            then "MY"
    when {{ column }}   = "Maldives"
                                                                                            then "MV"
    when {{ column }}   = "Mali"
                                                                                            then "ML"
    when {{ column }}   = "Malta"
                                                                                            then "MT"
    when {{ column }}   in ("Marshall Islands (the)", "Marshall Islands")
                                                                                            then "MH"
    when {{ column }}   = "Martinique"
                                                                                            then "MQ"
    when {{ column }}   = "Mauritania"
                                                                                            then "MR"
    when {{ column }}   = "Mauritius"
                                                                                            then "MU"
    when {{ column }}   = "Mayotte"
                                                                                            then "YT"
    when {{ column }}   = "Mexico"
                                                                                            then "MX"
    when {{ column }}   in ("Micronesia (Federated States of)", "Micronesia")
                                                                                            then "FM"
    when {{ column }}   in ("Moldova (the Republic of)", "Moldova")
                                                                                            then "MD"
    when {{ column }}   = "Monaco"
                                                                                            then "MC"
    when {{ column }}   = "Mongolia"
                                                                                            then "MN"
    when {{ column }}   = "Montenegro"
                                                                                            then "ME"
    when {{ column }}   = "Montserrat"
                                                                                            then "MS"
    when {{ column }}   = "Morocco"
                                                                                            then "MA"
    when {{ column }}   = "Mozambique"
                                                                                            then "MZ"
    when {{ column }}   in ("Myanmar", "Myanmar (Burma)")
                                                                                            then "MM"
    when {{ column }}   = "Namibia"
                                                                                            then "NA"
    when {{ column }}   = "Nauru"
                                                                                            then "NR"
    when {{ column }}   = "Nepal"
                                                                                            then "NP"
    when {{ column }}   in ("Netherlands (the)", "Netherlands", "Caribbean Netherlands")
                                                                                            then "NL"
    when {{ column }}   = "New Caledonia"
                                                                                            then "NC"
    when {{ column }}   = "New Zealand"
                                                                                            then "NZ"
    when {{ column }}   = "Nicaragua"
                                                                                            then "NI"
    when {{ column }}   in ("Niger (the)", "Niger")
                                                                                            then "NE"
    when {{ column }}   = "Nigeria"
                                                                                            then "NG"
    when {{ column }}   = "Niue"
                                                                                            then "NU"
    when {{ column }}   = "Norfolk Island"
                                                                                            then "NF"
    when {{ column }}   in ("Northern Mariana Islands (the)", "Northern Mariana Islands")
                                                                                            then "MP"
    when {{ column }}   = "Norway"
                                                                                            then "NO"
    when {{ column }}   = "Oman"
                                                                                            then "OM"
    when {{ column }}   = "Pakistan"
                                                                                            then "PK"
    when {{ column }}   = "Palau"
                                                                                            then "PW"
    when {{ column }}   in ("Palestine, State of", "Palestine")
                                                                                            then "PS"
    when {{ column }}   = "Panama"
                                                                                            then "PA"
    when {{ column }}   = "Papua New Guinea"
                                                                                            then "PG"
    when {{ column }}   = "Paraguay"
                                                                                            then "PY"
    when {{ column }}   = "Peru"
                                                                                            then "PE"
    when {{ column }}   in ("Philippines (the)", "Philippines")
                                                                                            then "PH"
    when {{ column }}   = "Pitcairn"
                                                                                            then "PN"
    when {{ column }}   = "Poland"
                                                                                            then "PL"
    when {{ column }}   = "Portugal"
                                                                                            then "PT"
    when {{ column }}   = "Puerto Rico"
                                                                                            then "PR"
    when {{ column }}   = "Qatar"
                                                                                            then "QA"
    when {{ column }}   in ("Republic of North Macedonia", "North Macedonia")
                                                                                            then "MK"
    when {{ column }}   = "Romania"
                                                                                            then "RO"
    when {{ column }}   in ("Russian Federation (the)", "Russia")
                                                                                            then "RU"
    when {{ column }}   = "Rwanda"
                                                                                            then "RW"
    when {{ column }}   = "Réunion"
                                                                                            then "RE"
    when {{ column }}   in ("Saint Barthélemy", "St. Barthélemy")
                                                                                            then "BL"
    when {{ column }}   in ("Saint Helena, Ascension and Tristan da Cunha", "St. Helena")
                                                                                            then "SH"
    when {{ column }}   in ("Saint Kitts and Nevis", "St. Kitts & Nevis")
                                                                                            then "KN"
    when {{ column }}   in ("Saint Lucia", "St. Lucia")
                                                                                            then "LC"
    when {{ column }}   in ("Saint Martin (French part)", "St. Martin")
                                                                                            then "MF"
    when {{ column }}   in ("Saint Pierre and Miquelon", "St. Pierre & Miquelon")
                                                                                            then "PM"
    when {{ column }}   in ("Saint Vincent and the Grenadines", "St. Vincent & Grenadines")
                                                                                            then "VC"
    when {{ column }}   = "Samoa"
                                                                                            then "WS"
    when {{ column }}   = "San Marino"
                                                                                            then "SM"
    when {{ column }}   = "Sao Tome and Principe"
                                                                                            then "ST"
    when {{ column }}   = "Saudi Arabia"
                                                                                            then "SA"
    when {{ column }}   = "Senegal"
                                                                                            then "SN"
    when {{ column }}   = "Serbia"
                                                                                            then "RS"
    when {{ column }}   = "Seychelles"
                                                                                            then "SC"
    when {{ column }}   = "Sierra Leone"
                                                                                            then "SL"
    when {{ column }}   = "Singapore"
                                                                                            then "SG"
    when {{ column }}   in ("Sint Maarten (Dutch part)", "Sint Maarten")
                                                                                            then "SX"
    when {{ column }}   = "Slovakia"
                                                                                            then "SK"
    when {{ column }}   = "Slovenia"
                                                                                            then "SI"
    when {{ column }}   = "Solomon Islands"
                                                                                            then "SB"
    when {{ column }}   = "Somalia"
                                                                                            then "SO"
    when {{ column }}   = "South Africa"
                                                                                            then "ZA"
    when {{ column }}   = "South Georgia and the South Sandwich Islands"
                                                                                            then "GS"
    when {{ column }}   = "South Sudan"
                                                                                            then "SS"
    when {{ column }}   = "Spain"
                                                                                            then "ES"
    when {{ column }}   = "Sri Lanka"
                                                                                            then "LK"
    when {{ column }}   in ("Sudan (the)", "Sudan")
                                                                                            then "SD"
    when {{ column }}   = "Suriname"
                                                                                            then "SR"
    when {{ column }}   in ("Svalbard and Jan Mayen", "Svalbard & Jan Mayen")
                                                                                            then "SJ"
    when {{ column }}   = "Sweden"
                                                                                            then "SE"
    when {{ column }}   = "Switzerland"
                                                                                            then "CH"
    when {{ column }}   in ("Syrian Arab Republic", "Syria")
                                                                                            then "SY"
    when {{ column }}   in ("Taiwan (Province of China)", "Taiwan")
                                                                                            then "TW"
    when {{ column }}   = "Tajikistan"
                                                                                            then "TJ"
    when {{ column }}   in ("Tanzania, United Republic of", "Tanzania")
                                                                                            then "TZ"
    when {{ column }}   = "Thailand"
                                                                                            then "TH"
    when {{ column }}   = "Timor-Leste"
                                                                                            then "TL"
    when {{ column }}   = "Togo"
                                                                                            then "TG"
    when {{ column }}   = "Tokelau"
                                                                                            then "TK"
    when {{ column }}   = "Tonga"
                                                                                            then "TO"
    when {{ column }}   in ("Trinidad and Tobago", "Trinidad & Tobago")
                                                                                            then "TT"
    when {{ column }}   = "Tunisia"
                                                                                            then "TN"
    when {{ column }}   in ("Turkey", "Türkiye")
                                                                                            then "TR"
    when {{ column }}   = "Turkmenistan"
                                                                                            then "TM"
    when {{ column }}   in ("Turks and Caicos Islands (the)", "Turks & Caicos Islands")
                                                                                            then "TC"
    when {{ column }}   = "Tuvalu"
                                                                                            then "TV"
    when {{ column }}   = "Uganda"
                                                                                            then "UG"
    when {{ column }}   = "Ukraine"
                                                                                            then "UA"
    when {{ column }}   in ("United Arab Emirates (the)", "United Arab Emirates")
                                                                                            then "AE"
    when {{ column }}   in ("United Kingdom of Great Britain and Northern Ireland (the)", "United Kingdom")
                                                                                            then "UK"
    when {{ column }}   = "United States Minor Outlying Islands (the)"
                                                                                            then "UM"
    when {{ column }}   in ("United States of America (the)", "United States")
                                                                                            then "US"
    when {{ column }}   = "Uruguay"
                                                                                            then "UY"
    when {{ column }}   = "Uzbekistan"
                                                                                            then "UZ"
    when {{ column }}   = "Vanuatu"
                                                                                            then "VU"
    when {{ column }}   in ("Venezuela (Bolivarian Republic of)", "Venezuela")
                                                                                            then "VE"
    when {{ column }}   in ("Viet Nam", "Vietnam")
                                                                                            then "VN"
    when {{ column }}   in ("Virgin Islands (British)", "British Virgin Islands")
                                                                                            then "VG"
    when {{ column }}   in ("Virgin Islands (U.S.)", "U.S. Virgin Islands")
                                                                                            then "VI"
    when {{ column }}   = "Wallis and Futuna"
                                                                                            then "WF"
    when {{ column }}   = "Western Sahara"
                                                                                            then "EH"
    when {{ column }}   = "Yemen"
                                                                                            then "YE"
    when {{ column }}   = "Zambia"
                                                                                            then "ZM"
    when {{ column }}   = "Zimbabwe"
                                                                                            then "ZW"
    when {{ column }}   = "Åland Islands"
                                                                                            then "AX"

                                                                                            else "not_set"
end
{% endmacro %}